CREATE TABLE IF NOT EXISTS `kml_to_mysql` (
	`id` int(11) NOT NULL AUTO_INCREMENT,
	`name` varchar(100) COLLATE utf8_unicode_ci NOT NULL,
	`lat` double NOT NULL,
	`lng` double NOT NULL,
	PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=1;

INSERT INTO `kml_to_mysql` (`name`, `lat` ,`lng`, ) VALUES
("EL CHARCO DE LOS ADOBES", "", ""),
("EL CHARCO DE LOS ADOBES", "", ""),
("DEL SUR", "", ""),
("DEL SUR", "", ""),
("EL CERRITO", "", ""),
("EL CERRITO", "", ""),
("EL GRULLO CENTRO", "", ""),
("EL GRULLO CENTRO", "", ""),
("LAS FLORES", "", ""),
("LAS FLORES", "", ""),
("MIRADOR DEL ROSAL", "", ""),
("MIRADOR DEL ROSAL", "", ""),
("JARDINES DE MANANTLAN", "", ""),
("JARDINES DE MANANTLAN", "", ""),
("ORIENTE I SECCION", "", ""),
("ORIENTE I SECCION", "", ""),
("ORIENTE II SECCION", "", ""),
("ORIENTE II SECCION", "", ""),
("PATRIA", "", ""),
("PATRIA", "", ""),
("PALMA SOLA", "", ""),
("PALMA SOLA", "", ""),
("POCITO SANTO", "", ""),
("POCITO SANTO", "", ""),
("TEPOSILAMA", "", ""),
("TEPOSILAMA", "", ""),
("SANTA CECILIA", "", ""),
("SANTA CECILIA", "", ""),
("SAN PEDRO", "", ""),
("SAN PEDRO", "", ""),
("LAURELES", "", ""),
("LAURELES", "", ""),
("DEL ALAMO", "", ""),
("DEL ALAMO", "", ""),
("LA QUINTA", "", ""),
("LA QUINTA", "", "");
